apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-script.js: |-
    db = db.getSiblingDB('admin');

    db.createUser({
      user: "myuser",      
      pwd: "mypassword",   
      roles: [
        { role: "readWrite", db: "mydatabase" } 
      ]
    });
