apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    app: server
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  # Adjust if your Node.js app is running on a different port
      nodePort: 30005
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: bjnandi/crud-app-mern-server:v1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: CLOUDINARY_CLOUD_NAME
          value: "duwjbcn5x"

        - name: CLOUDINARY_API_KEY
          value: "246694643839175"

        - name: CLOUDINARY_API_SECRET
          value: "EFA0Qj8tD0f2-u_3Adx2I8ndHaY"

        - name: DB_USER
          value: myuser

        - name: DB_PASSWORD
          value: mypassword

        - name: DB_HOST
          value: mongodb-0.mongodb-svc.default.svc.cluster.local
