apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1  # Replace with your desired AWS region

nodeGroups:
  - name: worker
    instanceType: t2.small  # Replace with your desired EC2 instance type
    minSize: 1
    maxSize: 3
    desiredCapacity: 1